### ISSUE TITLE
Switchboard can potentially be broken by providing URL to a large file

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/switchboard-doc#3]
**NOTE: _Don't_ try this on a production machine or any machine that has critical services running on it!**

- Go to the Switchboard UI
- Enter the URL of a large file in the `Paste URL of the file to process` box
  - The one that lead to the broken service in my case was the ~6GB [europeana-old.tar.bz2](https://vlo.clarin.eu/resultsets/backups/europeana-old.tar.bz2)
- Submit
- After a minute or so, a modal dialogue appears indicating a failed upload

The problematic call seems the one to the `/download` back end service (e.g. https://weblicht.sfs.uni-tuebingen.de/clrs/download?input=https://proxybay.ist/) implemented by [python/main.py](https://github.com/clarin-eric/LRSwitchboard/blob/master/app/python/main.py).

For a very big file this will time out and give an error. However, it looks like the timeout occurs on the reverse proxy and the request may still processed in the back end, which then may or may not run out of memory. To be investigated...

**Comment by twagoo** [comment]
This is what happens with the server memory after passing a 733MB file through the `download` endpoint:
![Screenshot 2019-03-29 at 16 41 19](https://user-images.githubusercontent.com/7011396/55244446-80470280-5241-11e9-9710-e9ae5a785675.png)

**Comment by twagoo** [comment]
Some further testing shows that the system does seem to be capable of recovering from such request. Nevertheless the load becomes very high temporarily and services on that host including the switchboard itself may suffer substantial degradation of performance, so it would be good to restrict the amount of data passed through this call.

**Comment by emanueldima** [comment]
This has been fixed by limiting the data size, quite some time ago. It’s certainly fixed in v2.0.0.
